export const SET_STEP = "SET_STEP";
export const LOAD_STATE_SESSIONSTORAGE = "LOAD_STATE_SESSIONSTORAGE";

export const SET_PERSONAL_DATA = "SET_PERSONAL_DATA";

export const GET_DOCUMENTOS_PENDIENTES = "GET_DOCUMENTOS_PENDIENTES";

export const UPDATE_FORM = "UPDATE_FORM";

export const SAVE_TOKEN = "SAVE_TOKEN";

export const CLEAR_STATE = "CLEAR_STATE"